### ISSUE TITLE
How is deviceId generated

### ISSUE THREAD

**Issue by tuminzee** [basst314/ngx-webcam#101]
Is the deviceId generated by the library unique to all the devices?
Is is dependent on the physical id of the device?

**Comment by basst314** [comment]
Hi @tuminzee 

The deviceId is not generated by the library. It is returned by the browser API when accessing the webcam stream.

The Mozilla docs make it clear:
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/deviceId

> Device IDs are unique for a given origin, and are guaranteed to be the same across browsing sessions on the same origin. 

Hope that helps.

Cheers!

**Comment by tuminzee** [comment]
Thank you so much :smile:
