### ISSUE TITLE
camera preview on samsung tablet stretch/compress

### ISSUE THREAD

**Issue by rzlification** [basst314/ngx-webcam#103]
Hi, 

I face some issue with certain devices only, in this case, samsung tablet 2016. where the camera preview and the image snap is stretch. but i tested the same code using huawei tablet, it works just fine.

attach is the screenshot of the device info and camera preview when using the live-demo of ngx-webcam.

![1607931023875](https://user-images.githubusercontent.com/16426302/102054508-83728f80-3e24-11eb-9691-8321e3b544a7.JPEG)
![1607931023782](https://user-images.githubusercontent.com/16426302/102054513-84a3bc80-3e24-11eb-9041-a7563e7c84e4.JPEG)
![WhatsApp Image 2020-12-10 at 14 02 52](https://user-images.githubusercontent.com/16426302/102054051-bbc59e00-3e23-11eb-9deb-f07e05f5e7e6.jpeg)

**Comment by basst314** [comment]
Hi @rzlification,

thanks for attaching the images! Could you elaborate what exactly the issue is?
In the images provided I see the live camera view, but do not understand what the issue is.

Thank you!

**Comment by basst314** [comment]
Closed as no response from requester.
