### ISSUE TITLE
Not working on http based websites but works on localhost

### ISSUE THREAD

**Issue by KalpLathia** [basst314/ngx-webcam#107]
Hi everyone, 
I am implementing ngx-webcam(0.3.2) in my angular 11 project. It works fine while working on localhost, but its not working on live server. I dont know what went wrong. Please help me to figure it out as soon as possible.

Thanks.

**Comment by basst314** [comment]
Hi @KalpLathia,

Running on non-localhost domains requires https:// otherwise browsers block the necessary WebRTC APIs.

Please go theough the Readme.

Thanks!

**Comment by basst314** [comment]
Resolving, please re-open if issue persists.

**Comment by KalpLathia** [comment]
Thanks @basst314 for this quick response I will check with https:// and let you know if the issue still persists.
