### ISSUE TITLE
video options as Input()

### ISSUE THREAD

**Issue by davemecha** [basst314/ngx-webcam#11]
Thaks for this great simple component. Unfortunately there is an option missing to pass video options to the camera initialization.

In my case, I want to change the capture quality of the video, to make sure my snapshots are at the best possible resolution. Therefore I want to pass the additional parameters:

`width: { ideal: 4096 }, height: { ideal: 2160 }`

Currently the resolution is fixed to the screen resolution of the webcam module. This is not enough for many use cases.

**Comment by basst314** [comment]
Hi @davemecha,
thanks for raising this issue. #9 also goes into the same direction of passing more parameters for the webcam. I will try to address this soon.
Will keep you posted.

**Comment by basst314** [comment]
Hi @davemecha,

I released a [new version](https://github.com/basst314/ngx-webcam/releases/tag/0.1.6) of this library with a new feature to pass custom videoOptions to the webcam component. You should be able to specify your preferred resolutions with this feature now. The parameter you want to use is `videoOptions`.

Happy coding!
