### ISSUE TITLE
angular dependency problem

### ISSUE THREAD

**Issue by sknopp** [basst314/ngx-webcam#13]
I've got a problem while using this as dependency in my Angular 6 project.
This is what occurs on running my project after a npm-command:
```bash
sebastian@host:/path/to/my-project# ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-05-28T07:57:28.759Z
Hash: 2a73bb04a45e6f8c070a
Time: 14861ms
chunk {main} main.js, main.js.map (main) 1.97 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 703 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 69.7 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-webcam/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ℹ ｢wdm｣: Failed to compile.
```

Angular can't deal with multiple versions of itself installed in dependencies.
For me the solution was just deleting the `@angular` folder from `node_modules/ngx-webcam/node-modules` in my project. No further issues occured since then.

[This article](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/) seems to give a solution for that by just declaring angular as a `peer dependency`, so it is expected to be included by the dependent.

**Comment by basst314** [comment]
Hi @sknopp,
thanks for raising this issue. I am able to reproduce it and I'm working on a fix.
Will keep you posted!

**Comment by basst314** [comment]
Hi @sknopp,
I released a new version that should fix this issue:
https://github.com/basst314/ngx-webcam/releases/tag/0.1.5

Cheers!
