### ISSUE TITLE
mac does not open the webcam

### ISSUE THREAD

**Issue by andrejm7** [basst314/ngx-webcam#16]
Hi friend, I tested your library on mac but it did not open. Do you have a solution?

For my cell phone I also could not open the WebCam, but for the stackblitz I managed .. do you have something to indicate about this?

**Comment by basst314** [comment]
Hi @andrejm7,

Thanks for using this library. I just tested the demo page on my macbook and it works nicely.
Does the demo page work for you?
It strongly depends on the browser version you are using (and os on mobile devices).

Please try the demo page, and if it works for you, see the ngx-webcam-demo project as sample implementation.
If the demo doesn‘t work, I assume your device is not up to date enough to support the webRTC/UserMedia API which is required for this library to work.

Cheers!

**Comment by andrejm7** [comment]
Thanks @ basst314 for the fast return.

I'll test, but by stackblitz on my cell phone funcina and my project will not.
I practically did the same as the stackblitz. I do not know why the inconsistency.

**Comment by andrejm7** [comment]
Thanks @ basst314 for the fast return.

I'll test, but by stackblitz on my cell phone worked and my project did not.
I practically did the same as the stackblitz. I do not know why the inconsistency.

**Comment by andrejm7** [comment]
Thanks @basst314 for the fast return.

I'll test, but by stackblitz on my cell phone worked and my project did not.
I practically did the same as the stackblitz. I do not know why the inconsistency.

**Comment by andrejm7** [comment]
@basst314 The only difference is that the Stackblitz is on HTTPS and my project still this HTTP

Do you think that might be why?

**Comment by basst314** [comment]
Hi @andrejm7,

this might very well be the case. I tried to run the demo on an insecure location (http), and the webcam didn't open. I got a warning in my browser console that said:

`[Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

So, seems like you're right and you should switch your server to https to resolve this issue. 

For local development however, it runs fine with http on localhost.

Cheers!

**Comment by andrejm7** [comment]
muito obrigado. meu projeto ainda esta em desenvolvimento.. certamente passarei para https.

obrigado.

**Comment by andrejm7** [comment]
thank you so much. My project is still under development .. I will certainly switch to https.

thank you.

**Comment by andrejm7** [comment]
thank you so much. My project is still under development .. I will certainly switch to https.

thank you.
