### ISSUE TITLE
Firefox does not return deviceId for active device

### ISSUE THREAD

**Issue by basst314** [basst314/ngx-webcam#22]
When the demo page of this library is run in Firefox, the active device's `deviceId` is not returned when the camera is being activated. In the console it shows `active device: undefined`.

However, `WebcamUtils.getAvailableVideoInputs()` returns the video devices with `deviceId`.

Originally raised by @rajgsdei in #21.

**Comment by basst314** [comment]
Hi @rajgsdei,

I published a new version of this library ([0.1.8](https://github.com/basst314/ngx-webcam/releases/tag/0.1.8)) that fixes this issue. 
Could you please verify that in your project the deviceId is now being returned in Firefox?

Again, thanks for raising this issue.

Cheers!

**Comment by rajgsdei** [comment]
Hi @basst314,

I will update the package and verify this issue very soon and let you know.

Thanks.

**Comment by rajgsdei** [comment]
Hi @basst314,

I have checked the current package and it seems to be working fine on Firefox. That's what I needed in my application.

Thank you for taking quick action and fixing it on short notice.

Cheers!

**Comment by basst314** [comment]
Thanks @rajgsdei for verifying!
I‘m glad te issue is resolved now.
