### ISSUE TITLE
enumerateDevices not supported in chrome ios

### ISSUE THREAD

**Issue by musso** [basst314/ngx-webcam#26]
When using Chrome in iOS, there is an error message "enumerateDevices() not supported".

**Comment by gagan95** [comment]
Unable use webcam on Chrome >53, Firefox >38 
{ "message": "enumerateDevices() not supported." }
{ "message": "Cannot read UserMedia from MediaDevices." }
on windows and ubuntu

**Comment by jeneiro** [comment]
> Unable use webcam on Chrome >53, Firefox >38
> { "message": "enumerateDevices() not supported." }
> { "message": "Cannot read UserMedia from MediaDevices." }
> on windows and ubuntu
> Everything works fine when using ng serve --aot but in production i'm facing the issue

i am facing the same issue

**Comment by gagan95** [comment]
hi @jeneiro , my issue got solved when i'm using my application over https the issue was http which won't enable your media devices due to security reasons

**Comment by basst314** [comment]
Hi @gagan95,

Thanks for helping out.

@jeneiro: yes, your app must be served over https://, see the „Prerequisites“ section in the README.

Hope that solves your issue.

Cheers!
