### ISSUE TITLE
not working on angular material modal

### ISSUE THREAD

**Issue by kenken64** [basst314/ngx-webcam#27]
having a blank screen.

**Comment by btxtiger** [comment]
You need to toggle the camera visibility to fix it. No idea why

**Comment by basst314** [comment]
Hi @btxtiger,

Thanks for raising this. Will take a look at it as soon as I have some time.

Could you provide more information on how you use ngx-webcam and md modal together? A minimal code example that shows the issue would be best.

Thanks!

**Comment by basst314** [comment]
Hi @kenken64 and @btxtiger,

Does the issue still happen with the latest version of ngx-webcam?
If so, please provide a minimal code example that shows the issue.

Thanks

**Comment by opiepj** [comment]
@basst314 can confirm this is happening, lose all state once the modal (where `<webcam></webcam>` resides in) closes.

**Comment by opiepj** [comment]
@basst314 I found a workaround, since the streams close if the <webcam> directive is no longer rendered, I had to pass create another stream that saved webcam data into a reference before closing. 

Think it's your `OnDestroy` method, but maybe this is a valid design.

**Comment by basst314** [comment]
Not exactly sure what you mean by that, but generally speaking the streams should be closed onDestroy. We don‘t want webcams to stay active if the component is not used anymore.

If you’re still experiencing issues, please provide a minimal code example in a new issue; closing this one.

Thanks
