### ISSUE TITLE
Need IE 11 Support

### ISSUE THREAD

**Issue by DSaralaya** [basst314/ngx-webcam#3]
Currently not supporting IE11.

**Comment by basst314** [comment]
Hi @DSaralaya, sorry for the late reply.

Unfortunately IE11 doesn't support WebRTC (the standard we use to access the webcam) yet.
See compatibility matrix at: http://iswebrtcreadyyet.com/ and [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Browser_compatibility).

As this library is supposed to be as lightweight as possible, it is an explicit goal to *not* build custom solutions for off-standard browsers who don't support these features.

So unfortunately, IE11 cannot be supported at this time. 
Should IE11 at any point in the future support these standard features, it will automatically be supported. 

I will add this information to the Readme file, to make it easier for other users to find this information.

Cheers
