### ISSUE TITLE
Return the ImageData from the Canvas context

### ISSUE THREAD

**Issue by davidshen84** [basst314/ngx-webcam#30]
The `WebcamImage` object should contain the `ImageDate` from the canvas' context. So it would be easier to perform pixel-level manipulation on the captured image.

Sample: https://www.w3schools.com/tags/canvas_getimagedata.asp

**Comment by basst314** [comment]
Hi @davidshen84,

Thanks for raising this, it sounds like an interesting extension. I will read into it and provide an update on this thread soon.

Cheers!

**Comment by davidshen84** [comment]
https://davidshen84.github.io/#/webcam

Here's a simple application that makes use of this change.

*The layout doesn't work well on a small screen. *

**Comment by davidshen84** [comment]
Hi @basst314,

1. The memory size of the ImageData object should be *width * height *
4 *bytes.
I think it is a small size for desktop systems, but maybe a bit too much
for mobile systems.
2. I think that is hard to determine because it is platform dependent.
Theoretically, it only needs to copy the image, which is already in memory,
to a new memory location.

I think I can add a module level configuration to enable/disable this. What
do you think?


Thanks,
David

**Comment by davidshen84** [comment]
Hi @basst314 ,

Instead of adding a module level configuration, I decided to add a `captureImageData` attribute to the component. It's a boolean type value and the default value is `false`. This makes sure the component is backward compatible, and the developers have instance level control of this object.


Thanks.
