### ISSUE TITLE
Allow setting mimeType and imageQuality for `takeSnapshot`

### ISSUE THREAD

**Issue by wottpal** [basst314/ngx-webcam#33]
It would be super nice being able to set the quality of the taken screenshot (and it's mime-type).

Direct-Link to Function: https://github.com/basst314/ngx-webcam/blob/bc709625e76612337a9303f6d044358142d3b185/src/app/modules/webcam/webcam/webcam.component.ts#L193

Documentation of `toDataURL`: https://developer.mozilla.org/de/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by basst314** [comment]
Hi @wottpal,

Thanks for beinging this up. Sounds like a good extension to me.
I have a couple of things on my list now and I will work on them as soon as possible.
Probably during the holidays.

Thanks

**Comment by wottpal** [comment]
That would be 🔥 Thanks!

**Comment by basst314** [comment]
Hi @wottpal,

I'm happy to let you know that I implemented this feature. It's included in [version 0.2.1](https://github.com/basst314/ngx-webcam/releases/tag/0.2.1).

Check out the new parameters `imageType` and `imageQuality`. 

Cheers!
