### ISSUE TITLE
Camera Not working on iPhones

### ISSUE THREAD

**Issue by Pranay-K** [basst314/ngx-webcam#35]
Trying to use the DemoProject using ngx-webcam v2.0.0, which is not working.
Underneath are the captured errors

> enumeratedDevices() not supported

> Cannot read UserMedia from MediaDevices
The same app is working on android devices.

**Comment by basst314** [comment]
Hi Pranay-K,

The module works on iphones, as long as the iOS is up-to-date enough. I believe iOS started around version 11 to support the required userMedia APIs.
What version of iOS are you running?
Please try to update - the webcam should work then.

Cheers!

**Comment by balazsnemeth** [comment]
It happened for me in Chrome on iOS, are you sure you used Safari? On Safari, it works fine in my app

**Comment by basst314** [comment]
Hi @balazsnemeth,

Does the demo work for you?
https://basst314.github.io/ngx-webcam/?

Please also state your iPhone + iOS version.

Thanks

**Comment by basst314** [comment]
Thanks! I’m glad you could resolve the issue!
