### ISSUE TITLE
Error in production build

### ISSUE THREAD

**Issue by kabilya** [basst314/ngx-webcam#39]
Thank you for this awesome library.
I was about to do a production build (AOT) of our app 
but getting meta data error saying I have version 4 and expected was 3.

I'm using Angular 4.4.6  version and I thought this is compatible.

Thanks.

**Comment by basst314** [comment]
Hi @kabilya,

Can you share some more information about the issue you‘re experiencing?
* what version of ngx-webcam are you using?
* what version of angular?
* what‘s the exact error message?
* do you have a minimal eyample to reproduce?

Thanks!

**Comment by basst314** [comment]
no response from requester, closing this issue.

**Comment by tbatsenko** [comment]
Hi, 

I'm experiencing the same issue.
version of ngx-webcam: ^0.2.6

```
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/cli": "1.4.10",
```

 exact error message:
```
Metadata version mismatch for module /.../myapp/node_modules/ngx-webcam/ngx-webcam.d.ts, found version 4, expected 3, resolving symbol AppModule in /.../myapp/src/app/app.module.ts, resolving symbol AppModule in /../myapp/src/app/app.module.ts
```
 
The minimal example to reproduce: 
- install @angular/cli": "1.4.10",
- create a new app with ng new myapp
- insert import WebcamModule to your NgModule file
- insert <webcam> tag somewhere in your html
- run ng serve, if runs ok, terminate and try to run again
