### ISSUE TITLE
Close the webcam without closing the tab ?

### ISSUE THREAD

**Issue by mahdifantar** [basst314/ngx-webcam#4]
i used this module and it's really helpful but i have a little problem is how to close the webcam without closing the tab. Any help please

**Comment by basst314** [comment]
Hi @mahdifantar,
what exactly are you trying to achieve?
Couldn't you just add `*ngIf="..."` to the webcam component tag?

**Comment by basst314** [comment]
Hi @mahdifantar,
I think I understand your problem. Even if you remove the webcam component with `*ngIf`, the webcam of the computer you're using is still active (mine shows a green light next to the webcam lens to indicate active use).
I'll try to look into this.

**Comment by basst314** [comment]
Hi @mahdifantar,
I just released a new version of this package: [0.1.3](https://github.com/basst314/ngx-webcam/releases). This issue has been fixed!
Cheers and thank you for using this package!
