### ISSUE TITLE
Last version in firefox/safari

### ISSUE THREAD

**Issue by Kromas** [basst314/ngx-webcam#40]
0.2.0 and above not working

**Comment by basst314** [comment]
Hi @Kromas,

The project-demo works fine for me in the latest FireFox v65.0.2 (64bit).

What issue are you experiencing? Please add more information about the issue (i.e. screenshots or console logs) and the device you're using (smartphone, laptop, etc.).

Thanks

**Comment by basst314** [comment]
Safari 12 on iOS 12.1 working fine.

@Kromas: please provide more information about what issues you‘re experiencing.

Thanks

**Comment by Kromas** [comment]
Hi @basst314 

Angular CLI: 6.0.8
Node: 8.11.3
Firefox: 65.0.2
From desktop

For now, im using "ngx-webcam": "0.1.8". The only problem i would like to fix is when i take a screenshot with a cellphone i got an image with more height than width and i need always something like 220px to 150px. Can i set this somewhere?

Thanks

**Comment by basst314** [comment]
Hi @Kromas,

What exactly is the issue you‘re experiencing with firefox?
I tested the live demo (see link in readme) with that ff version and it worked fine.

Could you share a minimal code example that reproduces the issue?

Thanks

**Comment by basst314** [comment]
Regarding height and width: the height/width parameter define the bounding box of the webcam preview. However the image returned after taking a screenshot will always have the resolution of the actual webcam stream and may be in landscape or portrait mode depending on the webcam/device and orientation. If you have to trim it to a specific format, you would have to do this in post processing.

**Comment by Kromas** [comment]
Hi @basst314 

Thanks for the answer about width/height, im going to see what i do with that.
Regarding the version problem, I reinstalled everything for the 3rd time and apparently I can use the camera with mozilla and webcam 0.2.2 =). I will check on iphone later.

Thanks!

**Comment by basst314** [comment]
Hi @Kromas,

Glad to hear that and thanks for confirming!

Cheers
