### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by clvs7-gh** [basst314/ngx-webcam#42]
Hello. 

I like your library, so I want to use this in production.
But, there is one problem; MIT license has specified into package.json, but actually LICENSE file is missing.
Considiring package.json, I think this project is MIT Licensed, but I cannot prove that without LICENSE file.
Just in case, would you please add LICENSE file?

MIT license template is here:
https://opensource.org/licenses/mit-license.php

Thank you.

**Comment by basst314** [comment]
Hi @clvs7-gh,

thanks for the heads-up, I added the license file.

Thanks for using this library!

Cheers
