### ISSUE TITLE
Button Type

### ISSUE THREAD

**Issue by ManuelSafaric** [basst314/ngx-webcam#43]
Hello, 

please change the Button type of triggerSnapshot(); to something like type="button".
This has cost me more time then i would like to admit. (This caused my form to submit)

Kind regards,
Manuel

**Comment by basst314** [comment]
Hi @ManuelSafaric,

Could you elaborate a little bit on what you mean exactly and what issues you are experiencing?

Thanks!

**Comment by ManuelSafaric** [comment]
The default button Type is submit, so when you use the ngx-webcam component inside a form e.g. click on the "Snanpshot" button it triggers the onSubmit Method.

**Comment by basst314** [comment]
Hi @ManuelSafaric,

the  <webcam> component does not include any button elements.

Could you share some example code maybe? Or are you referring to the demo page?

Thanks

**Comment by basst314** [comment]
No response from requester, closing.
