### ISSUE TITLE
Expose <video> element

### ISSUE THREAD

**Issue by franz1023dfjr** [basst314/ngx-webcam#44]
Hi! This library is great.

I was wondering if the `video` element could be made public. In that way i can pass it to other libraries like face-api.js

`// access video element` 
`const video = this.webcam.video; `
` // pass it as input to face-api.js`
`from(faceapi.detectSingleFace(video)).subscribe((result) => { })`

It would be great rather querying the element through `document`.
Thanks.

**Comment by basst314** [comment]
Hi @franz1023dfjr,

thank you for using this library!

The idea of exposing the video element sounds interesting. I will take a look at it and the face-api lib that you mentioned.

Am I correct in the assumption that you're currently able to use a workaround by querying the element through `document`?

Cheers

**Comment by franz1023dfjr** [comment]
Hi @basst314 ,

Yes. That's the lib I'm talking about and your library makes my work faster since i don't have to code setting up the camera. I greatly appreciate it.

Your assumption is correct. What I'm doing right now is: 
`const video = document.querySelector('#webcam video')`

Not much of a hassle but I rather use `@ViewChild()` decorator of angular ^_^ then access its properties .

Thanks.

**Comment by basst314** [comment]
Hi @franz1023dfjr,

I released a new version (0.2.4) which has a new method to access the native video element. Checkout the `nativeVideoElement()` method on the webcam component.

Cheers!
