### ISSUE TITLE
Constraints not respected on ImageData

### ISSUE THREAD

**Issue by dadebulba** [basst314/ngx-webcam#45]
Hi,
I'm using ImageData returned by the WebcamImage for doing some operations. The problem is that I set some constraints on the webcam videoOptions input but they are not respected.
Here's my code:
Html component
```
<webcam id="webcam" [height]="height" [width]="width" [trigger]="triggerObservable" (imageCapture)="handleImage($event)"
                *ngIf="showWebcam" [allowCameraSwitch]="allowCameraSwitch" [switchCamera]="nextWebcamObservable" [mirrorImage]="mirrorImage"
                [videoOptions]="videoOptions" [imageQuality]="1" (cameraSwitched)="cameraWasSwitched($event)" [captureImageData]="captureImageData"
                (initError)="handleInitError($event)" [videoOptions]="mediaConstraints"></webcam>
```

Ts component
```
public height : number = 256;
public width : number = 256;
public showWebcam = true;
public allowCameraSwitch = false;
public multipleWebcamsAvailable = false;
public deviceId: string;
public mirrorImage : string = "always";
public captureImageData : boolean = true;
public mediaConstraints = {
    video: {
      optional: [
        {minWidth: 720},
        {minWidth: 1024},
        {minWidth: 1280},
        {minWidth: 1920},
        {minWidth: 2560},
        {minHeight: 720},
        {minHeight: 1024},
        {minHeight: 1280},
        {minHeight: 1920},
        {minHeight: 2560}
      ]
    }
  }
```

Here is a function where i pass imageData object and it always log 480 x 640 as pixels dimension of the screenshot also with mobile it log 640 x 480 (because the screenshot is taken vertically)
```
 private imagedata_to_image(imagedata) {
  var canvas = document.createElement('canvas');
  var ctx = canvas.getContext('2d');
  canvas.width = imagedata.width;
  canvas.height = imagedata.height;
  console.log(`Image data height: ${imagedata.height}, Image data width: ${imagedata.width}`);
  ctx.putImageData(imagedata, 0, 0);

  var image = new Image();
  image.src = canvas.toDataURL();
  return image;
}
```
Is this issue related to the library or am I doing something wrong?

Thanks

**Comment by basst314** [comment]
Hi @dadebulba,

Are you sure your camera provides a higher resolution than 640x480?

The constraints that you pass into the lib get passed straight on to the browser API. But since they‘re passed as „optional“ constraints, they don‘t have to be fulfilled by the browser.

You can use this tool to see what resolutions your device supports:
https://webrtchacks.github.io/WebRTC-Camera-Resolution/

Also i think having the keyword „optional“ in your constraints is actually an older format, you might want to check out the current format of specifying constraints to see if it helps.

**Comment by dadebulba** [comment]
Sorry, my bad. I was focused on the code but the resolution of my camera is 640x480

**Comment by basst314** [comment]
Glad we got it sorted out!
