### ISSUE TITLE
webcam trigger snap not working on Chrome Incognito

### ISSUE THREAD

**Issue by poojas17** [basst314/ngx-webcam#46]
Webcam is triggering snaps on all browsers and their incognitos except Chrome incognito mode. 
Demo is working fine on incognito

**Comment by basst314** [comment]
Hi @poojas17,

Thanks for using this lib!
What do you mean by „demo is working fine in incognito“? I thought it would not be working? Or do you just experience issues when running your own app in incognito?

Can you share some more details about what exactly is happening?

Thanks!

**Comment by poojas17** [comment]
Hi @basst314 
Live demo given by ngx-webcam :https://basst314.github.io/ngx-webcam/? is working fine on my system. 
The issue seems to be intermittent on my app when running on different systems specifically on Chrome Incognito. It's working fine in normal tabs and on Mozilla/Firefox and their incognito mode as well.

**Comment by basst314** [comment]
Hi @poojas17,

There shouldn‘t be a difference between incognito and normal browsing. If you have permissions to access the cam it should be fine. 

Do you see any errors coming through the initError output of the component, or anything in the browser console?

When you try to trigger snapshots repeatedly, does it work sometimes? Or is it that when you encounter the error you are never able to trigger a single snap even when trying multiple times?

**Comment by poojas17** [comment]
Hi @basst314 
This problem occurs when the pop up comes to "Allow/Block" camera switch. 
There are no errors but there are console statements when the function is triggered.

Yes it works sometimes on some systems depending if the camera is allowed already. It appears to be permission issue on Chrome - If the user has "Allowed" already, the snap is triggered. However, if the user has "Ask" permission, the snap is not triggered even if the user allows camera switch.

**Comment by basst314** [comment]
Hi @poojas17,
this really sounds weird. Can you share some of the console statements you are seeing?
However, if the demo is working fine for you in Chrome incognito, then it seems like it's something with your app. Make sure to run the app on a secure ´https://´ url.

Can you share a link to the app so that I can test it?

**Comment by basst314** [comment]
No response from requestor. Closing this issue.
If the issue persists, feel free to reopen.
