### ISSUE TITLE
Cam does not get off if we click "Take Picture" before cam is ready

### ISSUE THREAD

**Issue by azeemkhalid04** [basst314/ngx-webcam#53]
Thank you for creating great component. Initially I was facing issue that Cam was not switched off and it was resolved by implementing *ngIf="". However, great work from my QA team, they have created another scenario and reported it again :-)

If user clicks on "Take Picture" before the cam is ready (i.e. A black screen appears while cam is getting ready and user clicks on button immediately), then cam does not get off even if we destroy the component and we have to refresh page to get re-initialize.

Is there any way to get status of cam (if it is ready to use), so that I may hide/disable "Take Picture" button until cam is ready?

Thanks in advance.

**Comment by basst314** [comment]
Hi @azeemkhalid04,

You could try waiting for the ’cameraSwitched’ event. It should fire after a camera has been initialized. This should happen after the user gave permissions.

Let me know if that works for you.

**Comment by azeemkhalid04** [comment]
> Hi @azeemkhalid04,
> 
> You could try waiting for the `cameraSwitched` event. It should fire after a camera has been initialized. This should happen after the user gave permissions.
> 
> Let me know if that works for you.

Hi @basst314 ,

Thanks for solution. It worked for me.

**Comment by basst314** [comment]
Thanks for letting me know! I‘m glad it worked for you!
