### ISSUE TITLE
Default Rear Camera View

### ISSUE THREAD

**Issue by mamoyko** [basst314/ngx-webcam#55]
Is there anyway to change the camera source into rear view as default?

Thanks for helping

**Comment by basst314** [comment]
Related to #59.

Can you try using the videoOptions input by specifying MediaTrackConstraints?
It has a ‚facingMode‘ property. Please also check the readme about the videoOptions property, there‘s a link to the MediaTrackConstraints docs.

Let me know if that helps.

Thanks!

**Comment by basst314** [comment]
Hi @mamoyko,

I was able to reproduce the issue. I fixed a glitch where user provided video constraints were not applied properly under some circumstances.
Fixed in version 0.2.6.

Specifying the preferred camera is possible through the videoOptions parameter, see Readme.

Cheers.
