### ISSUE TITLE
controls are not showing

### ISSUE THREAD

**Issue by sagar2071995** [basst314/ngx-webcam#62]
when i am opening the page controls on webcam video are not displaying . i have to enable it by right click and show control option.

**Comment by sagar2071995** [comment]
controls means pause ,mute  ,full screen ,download this option are not displaying on webcam video.

**Comment by basst314** [comment]
Hi @sagar2071995,

This library does not provide options like this, so I guess whatever you‘ve seen was something else.

Let me know if that helps.
