### ISSUE TITLE
Production mode Issue

### ISSUE THREAD

**Issue by jeneiro** [basst314/ngx-webcam#63]
ngx-webcam works on development mode perfectly using ng serve but when deployed on a server in production mode the webcam does not come on it shows the error across all browsers:
Error: Uncaught (in promise): enumerateDevices() not supported.

**Comment by basst314** [comment]
Hi @jeneiro,

Thanks for reaching out.

It seems that the browser you‘re using does not support the required webRTC/mediaDevice API.

What browser are you using?

Also, make sure to serve the app in a secure context over ’https://’.

Let me know if that helps.

**Comment by basst314** [comment]
Oh and try to see if this demo works for you: it uses a prod compiled version of the library:

https://basst314.github.io/ngx-webcam/?

**Comment by basst314** [comment]
No response from requester, closing this issue.
