### ISSUE TITLE
Adding box inside camera

### ISSUE THREAD

**Issue by dgraceffa** [basst314/ngx-webcam#65]
Hi,
I'm using your library to collect car-plate images for an OCR service.
It would be great having a box in the view when the camera is opened where the content has to be to help the user fixing in the centre only the car plate. 
Is this already a possible feature in the library or will it be available in the future? 
Regards in advance #

**Comment by basst314** [comment]
You could just use css to place another element ("box") on top of the webcam view to indicate where users should place their object. The webcam component is generic and does not support this custom behavior.
If you have further questions feel free to re-open this issue or a new one.
Thanks.

**Comment by intotecho** [comment]
I agree it is a common and useful use case. Here is my workaround to draw an SVG over the video
See https://stackoverflow.com/a/46318225/2023941 for the positioning of box div over the first.
Use something like this in the template

```
<div #container>
          <webcam 
          </webcam>
          <img id="target1" src="assets/my.svg" height="100" width="100" [ngStyle]="targetStyle()"/>
        </div>
```

And in the component:

```
public targetStyle(): any {
    let x = 100+ Math.random() * 100;
    let y = 100+ Math.random() * 100;
    return {
      'top': `${x}px`,
      'left': `${y}px`,
    }
  }
```
In a **global** stylesheet, you can add a frame around the video element.


```
webcam video {

    outline: 5px solid green;
    outline-offset: -15px;
    position: relative;
  }

```
