### ISSUE TITLE
suporte angular 9

### ISSUE THREAD

**Issue by andrejm7** [basst314/ngx-webcam#69]
npm WARN ngx-webcam@0.2.6 requires a peer of @angular/core@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by bobbydowling** [comment]
It works fine in Ng9.  Just ignore the warning for now.

**Comment by andrejm7** [comment]
update bro

**Comment by basst314** [comment]
Upgraded to support Angular 9, Typescript >= 3.7 in a new release (0.3.0).
