### ISSUE TITLE
Build Failed.

### ISSUE THREAD

**Issue by lexcaraig** [basst314/ngx-webcam#7]
![image](https://user-images.githubusercontent.com/15936424/37941802-9bd249f8-31a2-11e8-95af-2d3c202d8ab2.png)

Hi, i am encountering the above error. How do you resolve it? Thanks

**Comment by lexcaraig** [comment]
Fix this by updgrading the angular packages.

**Comment by basst314** [comment]
Hi @lexcaraig,
Just for the record: which angular versions did you use before/after the upgrade?

**Comment by lexcaraig** [comment]
for angular packages: `^5.2.9`
cli: `1.7.3`
