### ISSUE TITLE
How to detect available webcamera(s) before webcamera video component is visibile?

### ISSUE THREAD

**Issue by mspace** [basst314/ngx-webcam#74]
I'm using next code:

```
    <webcam *ngIf="webCameraEnabled"
            (initError)="handleInitError($event)" 
            [allowCameraSwitch]="true"
            (imageCapture)="imageCaptured($event)" 
            [trigger]="snapshotSource$">
    </webcam>
    <div *ngIf="!webCameraEnabled" class="my-auto mx-auto">{{initErrorMsg}}</div>
```

and my WebCameraComponent.ts

```
/**
 * ! WebCamera component works only if accessed from HTTPS.
 * HTTP works only on localhost.
 */
export class WebCameraComponent implements OnInit {

  // webcam snapshot trigger
  private readonly snapshotSource: Subject<void> = new Subject<void>();

  public webCameraEnabled: boolean = true;
  public initErrorMsg: string;

  // latest snapshot
  public capturedImage: WebcamImage;

  public get snapshotSource$(): Observable<void> {
    return this.snapshotSource.asObservable();
  }

 public handleInitError(webcamInitError: WebcamInitError): void {

    this.webCameraEnabled = false;
    console.log(webcamInitError);
    const errorName: string = webcamInitError && webcamInitError.mediaStreamError && webcamInitError.mediaStreamError.name;

    // tslint:disable-next-line: strict-type-predicates
    if (errorName !== null) {

      if (errorName === 'NotFoundError') {
        this.initErrorMsg = 'No camera found.';
      }

      if (errorName === 'NotAllowedError') {
        this.initErrorMsg = 'Camera access was not allowed by user.';
      }
    }
    else {
      this.initErrorMsg = webcamInitError.message;
    }
  }

  public makeSnapshot(): void {
    this.snapshotSource.next();
  }

  public imageCaptured(webcamImage: WebcamImage): void {
    this.capturedImage = webcamImage;
    console.log('received webcam image', webcamImage);
  }
}

```

Camera stream is opened in popup (bootstrap modal-dialog), but in case camera can not be accessed (i.e. not attached, any other reason), I hide **webcam** with *ngIf. What happens is that user sees for a moment how window resizes. I want to prevent that.

Is there a way to initialize **webcam** programatically and then show <video> html element. The other solution I was thinking also is to set **[height]** and **[width]** to some minimum value like *10* and then on some *webCamInitializationHandler* set new size to 640x480 or some bigger one.

How can upper be achieved? Basically how can I first initialize webcam without showing the webcam html (i.e. video element ...). If there is no error, that video container with html video element is showed. I hope it's clear enought.

**Comment by mspace** [comment]
Is perhaps using **WebcamUtil.getAvailableVideoInputs()** this the solution?

```
 public ngOnInit(): void {
    WebcamUtil.getAvailableVideoInputs().then((mediaDevices: MediaDeviceInfo[]) => {

      console.log(mediaDevices);

      if (mediaDevices && mediaDevices.length > 0) {
        this.webCameraEnabled = true;
      }
    });
  }
```

**Comment by siir** [comment]
First off, I don't think you need to do anything beforehand. I'll give you an option to check the initError output response of ngx-webcam, and something you can do to do yourself beforehand if that is what you really want to do.

### Option One

There is an error type returned for no video devices found from this package. `WebcamInitError` class has a mediaStreamError property (type DOMError) that you can check by its name. 

`WebcamInitError.mediaStreamError.name === 'NotFoundError'`

Read more in the exceptions section of MDN: [MediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia). This is what is getting called when the webcam component is initialized, and any errors bubble up to your application in class type `WebcamInitError`.

``` typescript
export class WebcamInitError {
  public message: string = null;
  public mediaStreamError: MediaStreamError = null;
}
```

component.ts

``` typescript
webcamInitError: WebcamInitError;
cameraInitError(webcamInitError: WebcamInitError) {
  this.webcamInitError = webcamInitError;
}
```

component.html

``` HTML
<webcam (initError)="cameraInitError($event)"></webcam>
<div class="no-cameras-error" *ngIf="!!webcamInitError">
  <p>No cameras found!!</p>
</div>
```

### Option Two

If you really want to check yourself beforehand, you can try what I do for a different purpose:

I do a check in my component's ngOnInit to read available video devices and get their respective capabilities like height/width to build a constraints object. You could do the same for your purposes before you enable the `<webcam>` with an `*ngIf` resolving to `true` on the webcam. You do not need to use the webcam package to see a device's webcam(s).

component.ts:

``` typescript
cameras: InputDeviceInfo[];
devicesReady: boolean;

ngOnInit() {
    navigator.mediaDevices.enumerateDevices()
      .then((devices: InputDeviceInfo[]) => {
        this.cameras = devices.filter((device: InputDeviceInfo) => device.kind === 'videoinput');
        if (cameras.length > 0) {
          this.devicesReady = true;
        } else {
          this.devicesReady = false;
        }
      })
      .catch(err => {
        console.log(err)
      });
}
```

component.html:

``` HTML
<webcam *ngIf="devicesReady"></webcam>
```

If you wanted to know more about the type coming back from enumerateDevices, type `InputDeviceInfo` extends `MediaDeviceInfo` with a method to get the device's capabilities. 

[Read more on MediaDeviceInfo](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo).

In the typescript definitions, the relevant ones: 

``` typescript
interface InputDeviceInfo extends MediaDeviceInfo {
    getCapabilities(): MediaTrackCapabilities;
}
interface MediaDeviceInfo {
    readonly deviceId: string;
    readonly groupId: string;
    readonly kind: MediaDeviceKind;
    readonly label: string;
    toJSON(): any;
}
```
