### ISSUE TITLE
Angular universal, turn off camera

### ISSUE THREAD

**Issue by ArcSoul** [basst314/ngx-webcam#76]
Hi there, I had a problem with my boss that the camera kept on even when the component was destroyed with ng if, so I used the old ways to proceed with the total shutdown of the camera and delete that recording icon from the tab, I expose the method I use.

```
(this.webcamComponent.nativeVideoElement as HTMLVideoElement).pause();
    (this.webcamComponent.nativeVideoElement as HTMLVideoElement).src = null;
    ((this.webcamComponent.nativeVideoElement as HTMLVideoElement).srcObject as MediaStream).getTracks().forEach(track => {
      track.stop();
    });
    (this.webcamComponent.nativeVideoElement as HTMLVideoElement).srcObject = null;
```

**Comment by kishoreaoe** [comment]
@ArcSoul , is this working fine.. could you please advise.. so can implement in my project as well.
