### ISSUE TITLE
Error after introducing webcam

### ISSUE THREAD

**Issue by luoxiao-xy** [basst314/ngx-webcam#77]
"@angular/cli": "~9.1.3",
"typescript": "~3.8.3"
"rxjs": "~6.5.4",

ERROR in node_modules/ngx-webcam/src/app/modules/webcam/webcam.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of DocDeviceModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-webcam) which declares WebcamModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by aakashguptaa** [comment]
how were you able to resolve this error ?
