### ISSUE TITLE
Camera is not released web we unload component from HTML.

### ISSUE THREAD

**Issue by ashish-markelytics** [basst314/ngx-webcam#80]
I am using code like this.
`<webcam [switchCamera]="videoDeviceChange$"
     *ngIf = "!isVideoMute && isPermissionGranted" >
 </webcam>`

When i mute or unload this component. camera light is still on.

**Comment by basst314** [comment]
Hi @ashish-markelytics,

can you please try with the latest version of ngx-webcam and let me know if this issue still persists?

Thanks!

**Comment by basst314** [comment]
Closing as no response from requestor
