### ISSUE TITLE
There is no pause & play webcam option.

### ISSUE THREAD

**Issue by farhaan008** [basst314/ngx-webcam#81]
After image capture i want to pause webcam for a moment meanwhile call a rest api (to verify face present in image) so in case of failure want to play webcam again for recapture.

**Comment by jbistis** [comment]
Something like this works...`  <webcam *ngIf="(webCameraEnabled && !!!haveImage); else elseBlock" [trigger]="triggerObservable"
    (imageCapture)="handleImage($event)" [allowCameraSwitch]="allowCameraSwitch"
    [imageQuality]="1" (initError)="handleInitError($event)"></webcam>
  <div *ngIf="!webCameraEnabled">{{initErrorMsg}}</div>
  <ng-template #elseBlock>
    <img [src]="webcamImage.imageAsDataUrl" />
  </ng-template>`

**Comment by basst314** [comment]
Hi @farhaan008,

this can be achieved by removing the webcam component from the page and displaying the captured image for a moment instead. If you need to re-capture, just add ngx-webcam again.

I'm resolving this issue. If your issue still persists, please feel free to reopen.

Thanks!
