### ISSUE TITLE
How to extract an image file type File?

### ISSUE THREAD

**Issue by jbistis** [basst314/ngx-webcam#82]
I am trying to extract an image file from the captured WebcamImage to save it to a storage bucket.  Has anyone accomplished that?

**Comment by basst314** [comment]
Hi @jbistis 

WebcamImage contains a method to extract the base64 encoded image data:
https://github.com/basst314/ngx-webcam/blob/master/src/app/modules/webcam/domain/webcam-image.ts#L32

You can then process and store as desired.

Cheers

**Comment by jbistis** [comment]
Thanks, any hints on how to convert imageAsBase64 output to an image File object?  I tried a few methods (// https://stackblitz.com/edit/angular-yzq2o7) and none working.

**Comment by jbistis** [comment]
Hi @basst314, it working, can close the issue.  Thanks

**Comment by prosidney** [comment]
what did you do @jbistis ?

**Comment by kishoreaoe** [comment]
@prosidney , we can convert the same to file object with help of below code logic, and send as multipart form data to your backend apis.

  handleCapturedImage(webcamImage: WebcamImage) {

    const arr = this.webcamImage.imageAsDataUrl.split(",");
    const mime = arr[0].match(/:(.*?);/)[1];
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    const file: File = new File([u8arr], this.imageName, { type: this.imageFormat })
    console.log(file);
}
