### ISSUE TITLE
Change camera source

### ISSUE THREAD

**Issue by PascalHonegger** [basst314/ngx-webcam#9]
I really like this component and its simplicity. I just wanted to ask if there is a way to change the active camera? As far as I can tell the current behaviour uses the "first" camera it can find, e.g. the rear camera of a smartphone. I would like to give my users the options to switch the camera, e.g. the selfie camera. To keep the ngx-webcam component simple I would recommend an observable which rotates between all available sources, similar to the camera trigger. A boolean to get whether more than one device exists would also be nice, but not mandatory.
Some other ideas:
* Provide some sort of selection / drop down, but that's probably too specific.
* Option to make clickOnImage change the camera automatically

**Comment by basst314** [comment]
Hi @PascalHonegger,
Thank you for the feedback. That feature is already on my roadmap. I will try to prioritize it and start working on it soon.
Cheers

**Comment by basst314** [comment]
Hi @PascalHonegger,

Thanks for your patience on this. Finally I have a little more time to work on this project, so I‘ll also try to address this issue.

I already looked into it, but it seems like the WebRTC/UserMedia interface doesn‘t provide information regarding available devices and their details like front-/back-facing.
But I‘ll spend some more time on it, as this is a really good enhancement imo!

Will keep you posted.

**Comment by basst314** [comment]
Hi @PascalHonegger,

I was able to resolve this issue and released a [new version](https://github.com/basst314/ngx-webcam/releases/tag/0.1.6) of this library which enables users and developers to switch between available webcams.

Happy coding!

**Comment by b-mi** [comment]
But created images are still of size 640x480, so images has low quality. Would you enter functional sample code?
