### ISSUE TITLE
Zooming capabilities

### ISSUE THREAD

**Issue by haiquangtran** [basst314/ngx-webcam#92]
Is it possible to have zooming capabilities on the camera?

For example, when it opens up the camera, I will be able to pinch zoom, or controls that zoom in or out.

**Comment by basst314** [comment]
Hi @haiquangtran,

this is not currently supported. You might be able to achieve this using some custom CSS/JS to crop the camera live view and the captured image.

I'm resolving this issue and will put it on my 'features to implement' list. 

Thanks!
