### ISSUE TITLE
ERROR TypeError: a.Subject is not a constructor

### ISSUE THREAD

**Issue by andrejm7** [basst314/ngx-webcam#94]
Hello my friend.

in production I am having this error ..

ERROR TypeError: a.Subject is not a constructor

it seems to me that it is in this code ..
  private trigger: Subject <void> = new Subject <void> ();

how can I solve?

**Comment by andrejm7** [comment]
are you going to fix it or can we leave the library?

**Comment by andrejm7** [comment]
@basst314

**Comment by basst314** [comment]
Hi @andrejm7,

what version of Angular and ngx-webcam are you using? Please try with the latest version of ngx-webcam and let me know if the issue persists.

Also, please double check that you're having a supported version of `RxJs` in your package.json dependencies (see README/Prerequisites section). 

Thanks!

**Comment by basst314** [comment]
Closing as no response from requester.
