### ISSUE TITLE
Webcam is not accessed when we deployed in server

### ISSUE THREAD

**Issue by surenred** [basst314/ngx-webcam#98]
I have few Queries?

1. I developed an application using ngx-webcam it is working well in development stage but when I moved it to the server the webcam doesn't showed up. It Look for the webcam in the server and when I click capture image it capture's an image and show entire black.

2.  Is the build process  in normal ng build -prod or we need to use any package for the build purpose like packagr or anything else.

3. SSL is mandatory to access the webcam?

**Comment by basst314** [comment]
Hi @surenred,

Make sure the app is served on a secure location using https:// protocol (see Readme / Prerequisites).

Https is mandatory in order to allow browsers to access the userMedia / webcam APIs.

Cheers!

**Comment by surenred** [comment]
@basst314 Thank you. I tried with https it is working well and good.
